/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthedChatRouteImport } from './routes/_authed.chat'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedInspectorRouteImport } from './routes/_authed.inspector'
import { Route as AuthedMemoryRouteImport } from './routes/_authed.memory'
import { Route as AuthedRecurrenceRouteImport } from './routes/_authed.recurrence'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedIncidentsIndexRouteImport } from './routes/_authed.incidents.index'
import { Route as AuthedIncidentsIdRouteImport } from './routes/_authed.incidents.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedChatRoute = AuthedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInspectorRoute = AuthedInspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMemoryRoute = AuthedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecurrenceRoute = AuthedRecurrenceRouteImport.update({
  id: '/recurrence',
  path: '/recurrence',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIncidentsIndexRoute = AuthedIncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIncidentsIdRoute = AuthedIncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AuthedChatRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/inspector': typeof AuthedInspectorRoute
  '/memory': typeof AuthedMemoryRoute
  '/recurrence': typeof AuthedRecurrenceRoute
  '/settings': typeof AuthedSettingsRoute
  '/incidents/$id': typeof AuthedIncidentsIdRoute
  '/incidents/': typeof AuthedIncidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AuthedChatRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/inspector': typeof AuthedInspectorRoute
  '/memory': typeof AuthedMemoryRoute
  '/recurrence': typeof AuthedRecurrenceRoute
  '/settings': typeof AuthedSettingsRoute
  '/incidents/$id': typeof AuthedIncidentsIdRoute
  '/incidents': typeof AuthedIncidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/chat': typeof AuthedChatRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/inspector': typeof AuthedInspectorRoute
  '/_authed/memory': typeof AuthedMemoryRoute
  '/_authed/recurrence': typeof AuthedRecurrenceRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/incidents/$id': typeof AuthedIncidentsIdRoute
  '/_authed/incidents/': typeof AuthedIncidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/chat'
    | '/dashboard'
    | '/inspector'
    | '/memory'
    | '/recurrence'
    | '/settings'
    | '/incidents/$id'
    | '/incidents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/chat'
    | '/dashboard'
    | '/inspector'
    | '/memory'
    | '/recurrence'
    | '/settings'
    | '/incidents/$id'
    | '/incidents'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/chat'
    | '/_authed/dashboard'
    | '/_authed/inspector'
    | '/_authed/memory'
    | '/_authed/recurrence'
    | '/_authed/settings'
    | '/_authed/incidents/$id'
    | '/_authed/incidents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/chat': {
      id: '/_authed/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthedChatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inspector': {
      id: '/_authed/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof AuthedInspectorRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/memory': {
      id: '/_authed/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthedMemoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recurrence': {
      id: '/_authed/recurrence'
      path: '/recurrence'
      fullPath: '/recurrence'
      preLoaderRoute: typeof AuthedRecurrenceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/incidents/': {
      id: '/_authed/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AuthedIncidentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/incidents/$id': {
      id: '/_authed/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof AuthedIncidentsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedChatRoute: typeof AuthedChatRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedInspectorRoute: typeof AuthedInspectorRoute
  AuthedMemoryRoute: typeof AuthedMemoryRoute
  AuthedRecurrenceRoute: typeof AuthedRecurrenceRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIncidentsIdRoute: typeof AuthedIncidentsIdRoute
  AuthedIncidentsIndexRoute: typeof AuthedIncidentsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedChatRoute: AuthedChatRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedInspectorRoute: AuthedInspectorRoute,
  AuthedMemoryRoute: AuthedMemoryRoute,
  AuthedRecurrenceRoute: AuthedRecurrenceRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIncidentsIdRoute: AuthedIncidentsIdRoute,
  AuthedIncidentsIndexRoute: AuthedIncidentsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
